Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: passcoach.App
      CodeUri: C:\Users\Tower\IdeaProjects\passCoach_lambda\passCoachFunction
      Runtime: java8
      Architectures:
        - x86_64